Patch 1
novuhq/novu pull request #1414
Opened 2022-10-04 05:59 UTC by fadkeabhi

Added translation for Sindhi language

2022-10-04 08:02 UTC, p-fernandez requested changes
Thanks for your PR! There is one change missing to be able to approve this. An entry for the new language is missing in this file:
[docs/docs/notification-center/react-components.md
](https://github.com/novuhq/novu/blob/bd7c2490725f031cb832ab8d801ad61ae9e293fc/docs/docs/notification-center/react-components.md?plain=1#L196)
Could you please add it? Thank you.

2022-10-04 09:11 UTC, fadkeabhi commented
added entry for language in [docs/docs/notification-center/react-components.md](https://github.com/novuhq/novu/blob/bd7c2490725f031cb832ab8d801ad61ae9e293fc/docs/docs/notification-center/react-components.md?plain=1#L196)

2022-10-04 23:21 UTC, scopsy approved these changes
Thank you so much for your contribution! Really appreciate it 🙏

2022-10-05 02:07 UTC, fadkeabhi commented
@p-fernandez I have made changes addressed by you. Please review them.

2022-10-05 08:28 UTC, p-fernandez approved these changes

2022-10-05 17:00 UTC, fadkeabhi commented on packages/notification-center/src/i18n/lang.ts
> +  | 'ta'
done as you said

2022-10-05 23:09 UTC, scopsy approved these changes

2022-10-05 23:09 UTC, merged