Added Kurdish translation files
novuhq/novu pull request #1437
Opened 2022-10-05 03:58 UTC by fadkeabhi

Added translation in Kurdish language

2022-10-05 11:23 UTC, p-fernandez requested changes

2022-10-05 11:23 UTC, p-fernandez commented on packages/notification-center/src/i18n/lang.ts
> +import { KU } from './languages/ki';
```suggestion
import { KU } from './languages/ku';
```
File name should be `ku.ts`.

2022-10-05 11:23 UTC, p-fernandez commented on packages/notification-center/src/i18n/languages/ku.ts
> +    notifications: 'ئاگادارکردنەوەکان',
This line gets translated to `Warnings` when reversing. Maybe it is better to find a more appropriate translation.

2022-10-05 11:23 UTC, p-fernandez commented on packages/notification-center/src/i18n/languages/ku.ts
> +    settings: 'دانانەوە',
This line gets translated to `installation` when reversing. Maybe it is better to find a more appropriate translation.

2022-10-05 13:54 UTC, fadkeabhi commented
There are no specific words for notifications and settings in Kurdish (somali) language. So given the words with nearest meaning.

2022-10-07 06:38 UTC, p-fernandez approved these changes

2022-10-07 06:39 UTC, merged