feat: Complete Changes module
novuhq/novu pull request #1477
Opened 2022-10-05 18:37 UTC by L-390

issue #1322

2022-10-05 23:03 UTC, scopsy reviewed
there was a few missing methods types needs to be changed based on the swagger docs :)

Could you please take a look at https://docs.novu.co/api/apply-changes/ to validate the contents?

2022-10-06 05:24 UTC, florian-lefebvre commented
#1357 has bien merged into main, please pull the changes. You'll have to extend thé WithHttp classique but I think that's all

2022-10-06 05:53 UTC, L-390 commented
I hope everything went alright when pulling it because it was a huge struggle to pull the new changes :)

2022-10-06 09:37 UTC, scopsy commented on packages/node/src/lib/changes/changes.ts
> +  }
@davidsoderberg do you think we have those types available at @novu/shared?

2022-10-06 13:50 UTC, florian-lefebvre commented on packages/node/src/lib/changes/changes.ts
> +    return await this.http.get(`/v1/changes`);
I haven't changed anything about this but you're right, v1 is not required (see https://github.com/novuhq/novu/blob/main/packages/node/src/lib/novu.ts#L34)

2022-10-06 13:53 UTC, florian-lefebvre requested changes

2022-10-06 13:53 UTC, florian-lefebvre commented on packages/node/src/lib/changes/changes.ts
> +export class Changes implements IChanges {
It must be `export class Changes extends WithHttp implements iChanges {`. This means you don't have to set the private http nor writing the constructor.

2022-10-06 13:53 UTC, florian-lefebvre commented on packages/node/src/lib/changes/changes.ts
> +import { AxiosInstance } from 'axios';
Replace with `import axios from 'axios',`. It won't be used but it's necessay for types coming with WithHttp

2022-10-06 14:51 UTC, L-390 commented
Alright I added the "withHTTP" and removed the /v1, at least if I understood everything correctly :)

2022-10-06 14:54 UTC, florian-lefebvre requested changes

2022-10-06 14:54 UTC, florian-lefebvre commented on packages/node/src/lib/changes/changes.ts
> +import AxiosInstance from 'axios';
replace AxiosInstance with axios ;)

2022-10-06 17:01 UTC, scopsy approved these changes

2022-10-06 17:13 UTC, merged

2022-10-08 08:16 UTC, nilesh-maurya commented
@L-390 Tests related to `Changes module` are failing now. can you update those ?

2022-10-08 08:19 UTC, nilesh-maurya commented on packages/node/src/lib/changes/changes.spec.ts
> +    expect(mockedAxios.get).toHaveBeenCalledWith('/v1/changes');
here it will be `/changes` instead of `/v1/changes`,  same goes other tests also.