Update activity-feed.md and templates.md documentation
novuhq/novu pull request #1549
Opened 2022-10-08 06:03 UTC by michizhou

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Update activity-feed.md and templates.md by fixing documentation

- **Why was this change needed?** (You can also link to an open issue here)

Changes were needed for improved readability and consistency

- Changed `organisational` to `organizational` in templates.md
- Fix grammatical errors and added or removed punctuation

- **Other information**:

2022-10-08 06:05 UTC, michizhou commented
@p-fernandez @scopsy @davidsoderberg Please feel free to let me know if additional changes are needed.

2022-10-10 12:32 UTC, p-fernandez requested changes
Some good additions but other bits that need to be rolled back.
🌟

2022-10-10 12:32 UTC, p-fernandez commented on docs/docs/platform/templates.md
> +The name used to identify the notification template when triggering it. A slugified version of the name will be generated after the notification was created. For example, a notification template with
Please keep the existing copy.

2022-10-10 12:32 UTC, p-fernandez commented on docs/docs/platform/templates.md
> +The notification group is used to group multiple notification templates into a single group (currently only used behind the scenes for organizational purposes). But, in the upcoming subscriber prefer
I am sorry but this copy doesn't provide improvements to be honest.
`organisational` is rightly spelled (british english). It is undecided an unique language variaton for the whole codebase.
@scopsy maybe something to agree and to add to the CONTRIBUTING.md file.

2022-10-10 12:32 UTC, p-fernandez commented on docs/docs/platform/templates.md
> +For email channels, you can either use our basic visual editor or a fully custom code with [handlebars variables](https://handlebarsjs.com/guide/).
Channel in Novu is any type of notification used: email, sms, etc. So the use here was rightfully singular. Please roll back the change.

2022-10-11 08:01 UTC, p-fernandez approved these changes
🌟

2022-10-11 08:10 UTC, merged