feat: i18n-dutch support
novuhq/novu pull request #1569
Opened 2022-10-08 13:35 UTC by Asmit2952

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds Dutch language support for Novu.
- **Why was this change needed?** (You can also link to an open issue here)
This PR fixes: #1568

2022-10-09 06:16 UTC, davidsoderberg commented
Hi @Asmit2952, I see on your Github profile that you are living in India 😄 Have you studied Dutch somewhere?

2022-10-09 06:19 UTC, Asmit2952 commented
> Hi @Asmit2952, I see on your Github profile that you are living in India 😄 Have you studied Dutch somewhere?

Took some extra classes when I was in my high school 😁

2022-10-09 06:20 UTC, Asmit2952 commented
I know a bit of Spanish and German as well 😁

2022-10-09 06:23 UTC, davidsoderberg approved these changes

2022-10-10 16:45 UTC, Asmit2952 commented on packages/notification-center/src/i18n/languages/nl.ts
> +    notifications: 'Meldingen',
Ohh yeah, my translation translates to announcement. Will fix that.

2022-10-10 16:47 UTC, Asmit2952 commented on docs/docs/notification-center/react-components.md
> +          <li><code>nl</code> (Dutch)</li>
Yupp

2022-10-10 16:51 UTC, Asmit2952 commented
Resolved all conflicts @p-fernandez

2022-10-11 08:00 UTC, p-fernandez requested changes

2022-10-11 08:00 UTC, p-fernandez commented on packages/notification-center/src/i18n/lang.ts
> +  | 'vi'
Remove these 2 please, as they are repeated in the Union.

2022-10-11 13:34 UTC, scopsy approved these changes
Thank you so much for your contribution! Really appreciate it 🙏

2022-10-11 13:49 UTC, merged