Feature to add i18n - Swedish Language Support
novuhq/novu pull request #1582
Opened 2022-10-09 10:25 UTC by akshitagupta15june

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature to add i18n - Swedish Language Support
- **Why was this change needed?** (You can also link to an open issue here)
Fixes issue 🚀 Feature: i18n - #1581 
- **Other information**:
-Kindly review and merge this PR

2022-10-09 10:28 UTC, akshitagupta15june commented
@davidsoderberg @p-fernandez @scopsy please review this pr
previously i gave a norwegian support pr too #1559

2022-10-10 05:46 UTC, davidsoderberg commented on packages/notification-center/src/i18n/languages/sv.ts
> +    notifications: 'meddelanden',
We should use big m here

2022-10-10 05:46 UTC, davidsoderberg commented on packages/notification-center/src/i18n/languages/sv.ts
> +    settings: 'inställningar',
We should use `I` here

2022-10-10 05:47 UTC, davidsoderberg commented on packages/notification-center/src/i18n/languages/sv.ts
> +    markAllAsRead: 'Markera allt som läst',
This should be `Markera alla som lästa`

2022-10-10 05:47 UTC, davidsoderberg commented on packages/notification-center/src/i18n/languages/sv.ts
> +    poweredBy: 'poweredBy',
This should be translated with `Använder`

2022-10-10 05:48 UTC, davidsoderberg requested changes
The translation have some errors, please correct those...

2022-10-10 05:54 UTC, akshitagupta15june commented
Sure i will correct it

2022-10-10 06:16 UTC, akshitagupta15june commented
@davidsoderberg please review

2022-10-10 06:17 UTC, davidsoderberg approved these changes

2022-10-10 06:28 UTC, akshitagupta15june commented
@davidsoderberg all checks have passed

2022-10-10 06:33 UTC, merged