feat: add Google Analytics for documentation pages
novuhq/novu pull request #1710
Opened 2022-10-13 13:18 UTC by andrewgolovanov

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs: This pull request adds Google Analytics for documentation pages
- **Why was this change needed?** (You can also link to an open issue here)
We don't currently collect analytics from the documentation pages
- **Other information**:
N/A

2022-10-13 17:34 UTC, scopsy approved these changes

2022-10-13 19:31 UTC, p-fernandez requested changes

2022-10-13 19:31 UTC, p-fernandez commented on docs/package.json
> +    "@docusaurus/plugin-google-gtag": "^2.1.0",
Adding a new package will change the pnpm lock file, so we need it updated in the PR.

2022-10-14 11:33 UTC, scopsy approved these changes
thank you!

2022-10-14 11:33 UTC, merged