docs: Updated Email.js provider documentation page
novuhq/novu pull request #1727
Opened 2022-10-14 13:00 UTC by akarsh-jain-790

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes: [[NV-909] - Create a Email.js provider documentation page ](https://github.com/novuhq/novu/issues/1665)

2022-10-14 13:23 UTC, p-fernandez requested changes

2022-10-14 13:23 UTC, p-fernandez commented on docs/docs/channels/email/emailjs.md
> +You can use the [Email.js](https://www.emailjs.com/) provider to send transactional emails to your customers using the Novu Platform with a single API to create multi-channel experiences.
I am sorry but I don't find this is an improvement to the existing text.

2022-10-14 13:23 UTC, p-fernandez commented on docs/docs/channels/email/emailjs.md
> +It is suggested that you create a new API key for use with Novu. To successfully send emails, you will need to add the following permissions to your API key:
This bit doesn't make sense. It is incomplete.
Also I couldn't find any recommendation from Email.js to create a different API key for different consumers from the same owner.

2022-10-14 13:23 UTC, p-fernandez commented on docs/docs/channels/email/emailjs.md
> +Email.js keeps your authentication details on the server-side, and the client-side code just triggers a predefined email template, similarly to how any client-server application is working.
This bit belongs to this area: https://www.emailjs.com/docs/faq/cant-i-use-services-like-sendgrid-or-mandrill-directly/
It tries to explain the benefits of using Email.js when dealing with other services. To be honest, has little relation to the purpose of this documentation that is to teach to the users how to integrate this provider in Novu.

2022-12-01 11:38 UTC, scopsy commented
Closing this one due to in activity 🙏

2022-12-01 11:38 UTC, closed without merging