Fixed all grammar issues and typos in README.md
novuhq/novu pull request #1747
Opened 2022-10-16 13:32 UTC by bishal7679

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
   docs update 

- **Why was this change needed?** (You can also link to an open issue here)

   There are lot of grammar mistake and typos which should be fixed!

2022-10-16 13:36 UTC, bishal7679 commented
@jainpawan21 @davidsoderberg PTAL on this PR!

2022-10-17 08:51 UTC, p-fernandez requested changes

2022-10-17 08:51 UTC, p-fernandez commented on README.md
> +Building a notification system is hard, at first, it seems like just sending an email, but in reality, it's just the beginning. Users today expect a multi-channel communication experience via email,
Same comment as this previous PR with the same changes proposed: https://github.com/novuhq/novu/pull/1711#discussion_r995022955

2022-10-17 08:51 UTC, p-fernandez commented on README.md
> +Using the Novu API and admin panel you can easily add real-time notification center to your web-app without the hassle of building it yourself. You can use our React component or an IFrame embed if y
Same comment as this previos PR with the same change proposed: https://github.com/novuhq/novu/pull/1711#discussion_r995021703

2022-10-17 08:51 UTC, p-fernandez commented on README.md
> +Novu provides a single API to manage providers across multiple channels with a convenient interface.
Please rollback to the current copy. Thank you.

2022-10-18 18:15 UTC, bishal7679 commented
@p-fernandez PTAL again!

2022-10-19 06:44 UTC, scopsy approved these changes

2022-10-19 06:44 UTC, merged