Added a updated Readme File
novuhq/novu pull request #1777
Opened 2022-10-18 17:26 UTC by ShivamAgarwal-code

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
   This PR include the Readme.md update
- **Why was this change needed?** (You can also link to an open issue here)
These changes should be implemented to improve the integrity of the README
- **Other information**:
#1688 
The changes looking good than the existing ones.
It follows contributing Guidelines and Code of Conduct

Please review and merge
Thanks

2022-10-28 08:05 UTC, p-fernandez requested changes
Thanks for your contribution. Please address the changes requested. 🙏🏻

2022-10-28 08:05 UTC, p-fernandez commented on README.md
> +Using the Novu API and admin panel you can easily add real-time notification center to your web-app without the hassle of building it yourself. You can use our React component or an iFrame embed if y
```suggestion
Using the Novu API and admin panel you can easily add real-time notification center to your web-app without the hassle of building it yourself. You can use our React component or an iframe embed if you are not using React.
```
Arguably this is an opinionated capitalisation that is not used by the W3C.
https://www.w3.org/TR/2011/WD-html5-20110525/the-iframe-element.html

2022-10-28 08:05 UTC, p-fernandez commented on README.md
> +- 💅 Easily manage notification over multiple channels
Existing copy is accurate. Please roll this change back.

2022-11-16 07:36 UTC, scopsy commented
Closing this for now due to inactivity.

2022-11-16 07:36 UTC, closed without merging