fix: #1753 added switches for secure boolean UI
novuhq/novu pull request #1782
Opened 2022-10-19 00:27 UTC by CursedRock17

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This was a bug fix in response to issue #1753.

- **Why was this change needed?** (You can also link to an open issue here)
In that issue somebody brought up features that weren't being used according to the docs so they should be removed. I both removed the Sender name for nodemailer and added switches instead of input for all booleans, specifically the Secure field. 

- **Other information**:

I looked through the documentation and noticed many other documentation pages are either missing information, or the page is incorrect and needs to be fixed.

2022-10-19 15:47 UTC, scopsy approved these changes
Perfect! Could you just revert the image path?

2022-10-19 19:23 UTC, CursedRock17 commented on docs/docs/platform/digest.md
> +![Workflow Photo](../../static/img/digest-flow.png)
That should have reverted the screenshot change, saw it working on docasaurus as well.

2022-10-20 10:03 UTC, scopsy commented on docs/docs/platform/digest.md
> +![Workflow Photo](../../static/img/digest-flow.png)
Thanks!

2022-10-20 10:04 UTC, scopsy commented
@CursedRock17 from the docs of nodemailer, seems like we can add the support to add the from name with the following syntax:

> from - The email address of the sender. All email addresses can be plain ‘[sender@server.com](mailto:sender@server.com)’ or formatted '“Sender Name” [sender@server.com](mailto:sender@server.com)', see [Address object](https://nodemailer.com/message/addresses/) for details

https://nodemailer.com/message/ 

Maybe we can create conditional the from string if a sendername exists? instead of removing this configuration option from the modal? 

What do you think?

2022-10-20 10:51 UTC, CursedRock17 commented
I definitely think that's a good idea, gives the users more options. Though, would this be better as an overall change, I haven't looked at the documentation for all of the providers in depth yet, but would this work for most of them as well. Just wondering if we should change the UI in general or if you just wanted a nodemailer provider fix here.

2022-10-23 08:39 UTC, scopsy commented
@CursedRock17 seems like we have here some unrelated commits regarding pushwoosh. Do you mind separating them to a different PR? 

Regarding the addition of the sender name, I think this change is only missing in nodemaielr since other provider are familiar with the senderFrom property on the API level. I believe we can only fix nodemailer in this PR and no need for other changes. Wdyt?

2022-10-23 15:25 UTC, CursedRock17 commented
@scopsy I agree we most likely don't need to make any other changes. As for pushwoosh I had just made a template for the new provider and it wasn't letting me create a new pull request, I'll get that cleared.

2022-10-24 20:08 UTC, CursedRock17 commented
@scopsy I'm going to close this pull request since it has all been merged.

2022-10-26 04:38 UTC, CursedRock17 commented
@scopsy I know it's very messy, but I should've gotten rid of the pushwoosher provider API for this Pull Request. If you can merge and close this one I will push that provider into a new Pull Request

2022-10-28 11:06 UTC, scopsy approved these changes

2022-10-31 16:40 UTC, p-fernandez requested changes

2022-10-31 19:48 UTC, CursedRock17 commented on libs/shared/src/consts/providers/credentials/provider-credentials.ts
> +  mailConfigBase[0],
No it doesn't I was having merging issues with other branches I should have cleared it up and updated the branch.

2022-10-31 19:48 UTC, CursedRock17 commented on README.md
> +- [Providers](https://github.com/novuhq/novu#providers)
I apologize I don't know why that changed so slightly.

2022-11-08 07:10 UTC, closed without merging