[WIP][NV-928] - Add cypress component test to OrganizationSelect component
novuhq/novu pull request #1843
Opened 2022-10-24 22:05 UTC by ludovicobesana

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) Component Testing

- **Why was this change needed?** (You can also link to an open issue here) https://github.com/novuhq/novu/issues/1457
Close #1457 

- **Other information**:

2022-10-24 22:08 UTC, ludovicobesana commented
@soundarrajan-official I've added some other tests, maybe we can work on this together

2022-10-28 00:09 UTC, ludovicobesana commented
@scopsy  Did you see this?

2022-10-31 13:08 UTC, p-fernandez requested changes
This is a good one! Let us know when it is not in draft anymore and is ready for a final review.

2022-10-31 13:08 UTC, p-fernandez commented on apps/web/src/components/layout/components/OrganizationSelect.cy.tsx
> +  // TEST 1
These comments doesn't provide much value. I would suggest you to remove them.

2022-10-31 13:08 UTC, p-fernandez commented on apps/web/src/components/layout/components/OrganizationSelect.cy.tsx
> +    );
This test is missing the check. Like this has no difference with the render test.

2022-11-17 10:44 UTC, ludovicobesana commented
@scopsy I'll work on this today, so we can close this Issue.
Thank you

2022-12-08 03:59 UTC, scopsy commented
Closing the PR due to inactivity, @ludovicobesana feel free to reopen it once you are ready 🙏

2022-12-08 03:59 UTC, closed without merging