added bug report section
novuhq/novu pull request #1859
Opened 2022-10-26 15:23 UTC by saimaheshtaduri

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Added a section on bug report

- **Why was this change needed?** (You can also link to an open issue here)
- Fixes #1837

2022-10-26 15:25 UTC, saimaheshtaduri commented
@nevo-david @scopsy please review

2022-10-28 07:38 UTC, p-fernandez requested changes

2022-10-28 07:38 UTC, p-fernandez commented on CONTRIBUTING.md
> +If you would like to _resolve_ it, an issue with your proposal must be submitted first, to be sure that we can use it. Please consider the guidelines given below.
I just find this is a duplication of the entry `Submitting an issue`. What we can take of this is to update the links used in `Submitting an issue` and add both of the waits of submitting the issue.

2022-11-14 06:13 UTC, scopsy commented
Tend to aggree with @p-fernandez that it's a bit of a duplication for submitting an issue. For now, will close this PR. Thank you for your contribution nonetheless 🙏

2022-11-14 06:13 UTC, closed without merging