Improved subscriber.md
novuhq/novu pull request #1873
Opened 2022-10-27 15:22 UTC by Abubakrce19

Spotted some crucial grammatical error.
Thank you

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **Why was this change needed?** (You can also link to an open issue here)

- **Other information**:

2022-10-27 20:33 UTC, p-fernandez requested changes

2022-10-27 20:33 UTC, p-fernandez commented on docs/docs/platform/subscribers.md
> +Novu will create a subscriber if one does not exist, and will update existing subscribers based on the identified payload. You can call this function during registration or signup to make sure the su
```suggestion
Novu will create a subscriber if one does not exist, and will update existing subscribers based on the `identify` payload. You can call this function during registration or signup to make sure the subscriber data is up to date.
```
Identify is the right word. It is the method used to provide subscribers data. Let's leave it and put into backticks so we a reader can understand we are talking about a method from the codebase.

2022-10-28 05:41 UTC, Abubakrce19 commented
@p-fernandez 
Thank you soo much for correcting me.
Changes are done.
Please have a look now.

2022-10-28 07:27 UTC, p-fernandez approved these changes

2022-10-28 07:27 UTC, merged