i18n support for Bosnian language
novuhq/novu pull request #1875
Opened 2022-10-27 18:14 UTC by abhilipsasahoo03

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added i18n support for Bosnian language
- **Why was this change needed?** (You can also link to an open issue here)
Fixes #1860

2022-10-27 18:16 UTC, abhilipsasahoo03 commented
@davidsoderberg @scopsy kindly review!

2022-10-28 07:32 UTC, p-fernandez requested changes
Please update your branch with the latest changes we added in `main`. Now the file https://github.com/novuhq/novu/blob/main/packages/notification-center/src/i18n/lang.ts is being sorted alphabetically.

2022-10-28 18:44 UTC, abhilipsasahoo03 commented
Hey @p-fernandez i have made the required changes! Kindly take a look!

2022-10-31 08:18 UTC, p-fernandez requested changes

2022-10-31 08:18 UTC, p-fernandez commented on docs/docs/notification-center/react-components.md
> +          <li><code>bs</code> (Bosnian)</li>
This is not alphabetically sorted by the iso language code. Could you please ammend?

2022-10-31 08:18 UTC, p-fernandez commented on docs/docs/notification-center/react-components.md
> +          <li><code>bs</code> (Bosnian)</li>
Also if you can help us moving the albanian code to its proper place, we would appreciate it.

2022-10-31 14:41 UTC, abhilipsasahoo03 commented
@p-fernandez @djabarovgeorge I've reordered the list. Please take a look!

2022-10-31 14:48 UTC, p-fernandez approved these changes
🌟

2022-10-31 14:57 UTC, abhilipsasahoo03 commented
> 🌟 

Kindly merge :)

2022-10-31 15:01 UTC, merged