chore: Improved quick-start.md
novuhq/novu pull request #1896
Opened 2022-10-28 14:56 UTC by Abubakrce19

This changes the minor but crucial grammatical and spelling errors.

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs
- **Why was this change needed?** (You can also link to an open issue here)

- **Other information**:

2022-10-28 15:23 UTC, Abubakrce19 commented
@p-fernandez 
please have a look
Thank you

2022-10-28 15:27 UTC, p-fernandez requested changes

2022-10-28 15:27 UTC, p-fernandez commented on docs/docs/overview/quick-start.md
> +Novu will create an upsert command, and either create a subscriber with a specified payload, or update the existing subscriber with the passed information.
```suggestion
Novu will create an upsert command, and either create a subscriber with the specified payload, or update the existing subscriber with the passed information.
```

2022-10-28 16:25 UTC, Abubakrce19 commented
@p-fernandez 
Changes done

2022-10-28 19:40 UTC, florian-lefebvre approved these changes

2022-10-30 10:31 UTC, ainouzgali approved these changes
Thanks @Abubakrce19 !

2022-10-30 11:07 UTC, Abubakrce19 commented
> Thanks @Abubakrce19 !

Thank you soo much for approving on weekend too.
I have to merged PR to novu and this one (approved) but still this is showing that i am nor eligible for the swags.
Pleasen help me resolve this matter.
![image](https://user-images.githubusercontent.com/104122959/198875208-9ae14193-f064-4e8a-ae56-c2015ff76300.png)

2022-10-30 11:08 UTC, Abubakrce19 commented
@ainouzgali 
Please merge my Pr before october ends.
I am not counted for swags yet.

2022-10-30 11:12 UTC, merged