Corrected  the flow and grammar in code_of_conduct.md file
novuhq/novu pull request #1901
Opened 2022-10-28 17:57 UTC by Vanshiii203

- **What kind of change does this PR introduce?** 
This PR updates the docs to make text flow better.

- **Why was this change needed?** 
issue #1897

2022-10-29 17:40 UTC, Vanshiii203 commented
@p-fernandez Please review and merge this

2022-10-30 15:29 UTC, Vanshiii203 commented
@ainouzgali Can you please review and merge this?

2022-10-31 08:14 UTC, p-fernandez requested changes

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +ethnicity, sex characteristics, gender identity, or level of experience.
You removed education, socio-economic status, nationality, race, religion and sexual orientation. Please add them back.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +diverse, inclusive, diverse and healthy community.
This adds repetition and it is not needed.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +Examples of unacceptable behaviour include:
There is not an agreement in the core maintainers of using british english. Most of the codebase and documentation is written in american english so this change it feels opinionated.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +* The use of sexualized language or imagery, as well as any form of sexual attention or advance.
```suggestion
* The use of sexualized language or imagery, as well as any form of sexual attention or advances of any kind.
```

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +* * Any other behaviour that could be considered inappropriate in a professional setting. 
Double asterisk.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +contrary to this Code of Conduct, and will communicate reasons for moderation
Not aligned is a better legal term in this case.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +All community leaders are obligated to respect the privacy and security of witnesses to any incident.
Roll back to previous copy as this one changes the original meaning intended.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +behaviour was inappropriate. A public apology may be requested.
Already flagged it before. Opinionated.

2022-10-31 08:14 UTC, p-fernandez commented on CODE_OF_CONDUCT.md
> +**Community Impact**: Demonstrating a pattern of violating community standards, such as persistent inappropriate behavior, harassment of individuals, or aggression toward or disparagement of groups o
I consider sustained is more precise in the goal of this point as it gives the meaning of a lesser frequency than persistent.

2022-11-14 06:17 UTC, scopsy commented
Hi @Vanshiii203 did you had a chance to take a look at @p-fernandez comments? Let me know if you will have the time for that.

2022-11-24 08:52 UTC, scopsy commented
Closing this for now due to inactivity. 🙏

2022-11-24 08:52 UTC, closed without merging