feat: Add Feeds Module to node package
novuhq/novu pull request #1903
Opened 2022-10-28 18:37 UTC by viveknshah

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Completes the [feeds module](https://docs.novu.co/api/create-feed/ for @novu/node.
- **Why was this change needed?** (You can also link to an open issue here)
This resolves #1324 
- **Other information**:

2022-10-28 19:38 UTC, florian-lefebvre requested changes
Great work! I've only noticed a small change

2022-10-28 19:38 UTC, florian-lefebvre commented on packages/node/src/lib/feeds/feeds.ts
> +import { WithHttp } from '../novu.interface';
```suggestion
import axios from 'axios';
import { WithHttp } from '../novu.interface';
```
Even if not use, I believe it's required in order to work with `WithHttp`

2022-10-28 20:09 UTC, florian-lefebvre approved these changes

2022-10-30 10:23 UTC, viveknshah commented
Have updated the docs in https://github.com/novuhq/api-docs/pull/20

2022-10-31 12:45 UTC, p-fernandez approved these changes
🌟

2022-10-31 12:45 UTC, p-fernandez commented on packages/node/src/lib/feeds/feeds.spec.ts
> +describe('test use of novus node package - Feeds class', () => {
```suggestion
describe('Use of Novu node package - Feeds class', () => {
```

2022-10-31 13:54 UTC, merged