Added the article
novuhq/novu pull request #1947
Opened 2022-11-01 15:06 UTC by iqrafirdose

I added the article as a part of Hacktoberfest with aviyel.

### What kind of change does this PR introduce? 

- [ ] Bug
- [ ] Feature
- [x] Docs
- [ ] Other(s)

### Why was this change needed?

 

### Other information (Screenshots)

2022-11-01 17:50 UTC, p-fernandez requested changes

2022-11-01 17:50 UTC, p-fernandez commented on docs/docs/community/projects-and-articles.md
> +  Why do Notifications matter and shuld be used more in user flow?</a></li>
In the MD docs we need to use markdown. Please modify your PR to adapt the needs.

2022-11-27 11:47 UTC, iqrafirdose commented
> Hi @iqrafirdose do you mind to host this blog on `dev.to` or `hashnode` and submit a PR with the link to there instead of hosting the file on GitHub?

I publish the blog on hashnode and created a pull request #2103

2022-11-29 02:44 UTC, scopsy commented
Closing for #2103

2022-11-29 02:44 UTC, closed without merging