New Provider - Microsoft Outlook365
novuhq/novu pull request #2052
Opened 2022-11-20 09:54 UTC by cryptic-ai

### What change does this PR introduce? 
 
Creates a new email provider for Microsoft Outlook 360. 

### Why was this change needed?

Microsoft Outlook requires specific settings such as server, port, and TLS settings. To make it easier on new users coming to the platform to connect up to Outlook 365

### Other information (Screenshots)

![image](https://user-images.githubusercontent.com/11448029/202895506-e9467c2d-0dc4-46ae-9b72-3ca992a80ef1.png)

2022-11-22 10:37 UTC, p-fernandez requested changes
Thanks for this contribution.
The request change to use `From` in the config, rather than `User` as Outlook365 will need later is to unify the Email configs under one, and then we can map it inside of the provider like:
```
 user: this.config.from
 ```

2022-11-22 10:37 UTC, p-fernandez commented on libs/shared/src/consts/providers/credentials/provider-credentials.ts
> +];
I'd suggest to reuse the `mailConfigBase` and map the `User` property to the `From` property, then add the credential password.

2022-11-22 10:37 UTC, p-fernandez commented on providers/outlook365/src/lib/outlook365.provider.ts
> +      date: new Date().toISOString(),
Could we check if in the response Outlook 365 sends any timestamp that we could reuse here instead of setting it this way?

2022-11-22 15:56 UTC, p-fernandez commented
> @p-fernandez rebase / merge complete. that was more difficult than I thought it would be for some reason lol

Let me help you as you have multiple conflicts.

2022-11-22 16:21 UTC, closed without merging

2022-11-22 16:37 UTC, p-fernandez approved these changes
Just minor things and we are ready to go.
Thanks for your contribution. 🌟

2022-11-22 16:37 UTC, p-fernandez commented on providers/outlook365/README.md
> +```
Please add the usage. 🙏🏻

2022-11-22 16:37 UTC, p-fernandez commented on providers/outlook365/src/lib/outlook365.provider.ts
> +    });
We are not using `senderName` here.

2022-11-22 17:48 UTC, p-fernandez commented on providers/outlook365/src/lib/outlook365.provider.spec.ts
> +jest.mock('office365', () => {
```suggestion
jest.mock('./outlook365.provider', () => {
```

2022-11-23 15:10 UTC, BiswaViraj commented on providers/outlook365/src/lib/outlook365.provider.ts
> +  parseEventBody?: (body: any, identifier: string) => IEmailEventBody;
we can remove these two empty functions

2022-11-24 14:46 UTC, BiswaViraj commented
Hello @cryptic-ai , awesome work 🔥, 
could you look into the failing tests so that we can merge it soon 💪

2022-11-25 09:53 UTC, p-fernandez commented on providers/outlook365/src/lib/outlook365.provider.spec.ts
> +  get Outlook365Provider() {
You could also just mock individually the methods needed and not the entire module.

2022-11-28 12:30 UTC, p-fernandez commented
> @p-fernandez fixed the tests (thanks for your help on that!). Looks like I'm getting merge conflicts again. For some reason it's not letting me rebase locally. Would it be best if we closed this PR, and I just commit a new PR from a remote branch that's not a `next` clone to get rid of these issues?

Just give me 5 minutes as I am trying to do the rebase for you in my local.