Article
novuhq/novu pull request #2103
Opened 2022-11-27 11:45 UTC by iqrafirdose

### What change does this PR introduce? 

 

### Why was this change needed?

### Other information (Screenshots)

2022-11-28 14:58 UTC, p-fernandez requested changes

2022-11-28 14:58 UTC, p-fernandez commented on docs/docs/community/projects-and-articles.md
> +  Why do Notifications matter and should be use more in userflow?></li>
```suggestion
  - [Why do Notifications matter and should be use more in userflow?](https://github.com/iqrafirdose/novu/files/9915571/Why_do_Notifications_matter_and_should_be_used_more_in_user_flow.1.md)
```

2022-11-29 02:44 UTC, scopsy approved these changes

2022-11-29 08:14 UTC, p-fernandez approved these changes

2022-11-29 08:14 UTC, merged