fix: add reply to support for aws ses provider
novuhq/novu pull request #3131
Opened 2023-04-03 18:27 UTC by deep-bhatt-pmc

### What change does this PR introduce?

- This PR sets the replyTo parameter in nodemailer SES transport.

### Why was this change needed?

- `replyTo` wasn't working for AWS SES provider. This PR fixes that bug.

Closes #3122

2023-04-04 08:56 UTC, p-fernandez reviewed
I would suggest to add test for this addition for confidence.

2023-04-05 10:42 UTC, p-fernandez requested changes

2023-04-05 10:42 UTC, p-fernandez commented on providers/ses/src/lib/ses.provider.spec.ts
> +  replyTo: 'test@test1.com',
I think that this is not enough to test if `replyTo` is being configured in SES. 
In line 96 we should modify the spy to check that the proper params and values are passed by checking with the method `toHaveBeenCalledWith` and the values passed in the `mockNovuMessage`.
Unfortunately it wasn't done properly before but if not doing it we can't validate this change. 🙁

2023-04-09 05:28 UTC, deep-bhatt-pmc commented
> I would suggest to add test for this addition for confidence.

btw. @p-fernandez  Not sure if you have been notified, but I have updated the PR, can you please check?

2023-04-10 07:15 UTC, scopsy commented
Looks great!

2023-04-12 09:34 UTC, merged