feat(provider): Add africastalking provider
novuhq/novu pull request #3249
Opened 2023-04-20 00:42 UTC by peoray

### What change does this PR introduce?
Add Africastalking provider

Explain here the changes your PR introduces and text to help us understand the context of this change.

An updated version of #3102. Resolved all errors and make use of new changes introduced in the codebase.

### Why was this change needed?

Closes #1330 
### Other information (Screenshots)

2023-04-21 09:55 UTC, p-fernandez requested changes
Thank you for recreating the PR. Mostly changes based on the branding name of the provider. 🙏🏻

2023-04-21 09:55 UTC, p-fernandez commented on libs/shared/src/consts/providers/channels/sms.ts
> +    id: SmsProviderIdEnum.Africastalking,
Seeing the branded name I'd go for `AfricasTalking` / `africasTalking` capitalisation everywhere as needed.

2023-04-21 09:55 UTC, p-fernandez commented on libs/shared/src/consts/providers/channels/sms.ts
> +    displayName: 'Africastalking',
```suggestion
    displayName: `Africa's Talking`,
```

2023-04-21 09:55 UTC, p-fernandez commented on libs/shared/src/consts/providers/provider.enum.ts
> +  Africastalking = 'africastalking',
```suggestion
  AfricasTalking = 'africas-talking',
```

2023-04-21 09:55 UTC, p-fernandez commented on packages/application-generic/package.json
> +    "@novu/africastalking": "^0.13.0",
Sorry for being annoying but let's rename the folder and packaging name to `africas-talking` due the company's branding. 🙏🏻

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/README.md
> +  });
```suggestion
# Novu Africa's Talking Provider

A Africa's Talking SMS provider library for [@novu/node](https://github.com/novuhq/novu)

## Usage

```javascript
import { AfricasTalkingSmsProvider } from '@novu/africas-talking';

 const provider = new AfricasTalkingSmsProvider({
    apiKey: process.env.AFRICAS_TALKING_API_KEY,
    username: process.env.AFRICAS_TALKING_USERNAME,
    from: process.env.AFRICAS_TALKING_FROM
  });
```
Besides suggestions for the content, fixes for my suggested code naming based on the branding.

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/jest.config.js
> +  },
👏🏻

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/package.json
> +  "description": "A africastalking wrapper for novu",
```suggestion
  "description": "A Africa's Talking wrapper for Novu",
```

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/src/lib/africastalking.provider.spec.ts
> +test('should trigger africastalking library correctly', async () => {
```suggestion
test(`should trigger Africa's Talking library correctly`, async () => {
```
Suggestion for the trickier situations due branding apostrophe.

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/src/lib/africastalking.provider.spec.ts
> +    apiKey: 'b664b089f04b72c56ac3b0a8ffbb6f3d18a82eb40c29d17b49b84433439fb127',
Tell me it is not a real apiKey... 😅

2023-04-21 09:55 UTC, p-fernandez commented on providers/africastalking/src/lib/africastalking.provider.ts
> +      date: new Date().toISOString(),
Do we get any timestamp in the response of the call from the provider? If so, better use it that autogenerate it.

2023-04-21 10:16 UTC, peoray commented on providers/africastalking/src/lib/africastalking.provider.spec.ts
> +    apiKey: 'b664b089f04b72c56ac3b0a8ffbb6f3d18a82eb40c29d17b49b84433439fb127',
no it's not 😁

2023-04-22 08:37 UTC, peoray commented
@p-fernandez resolved

2023-05-02 10:57 UTC, p-fernandez approved these changes
2 small things and is done.
Also as we published the Novu version 0.14.0 you will need to upgrade the version number to 0.14.0. Also, very important the version of `@novu/stateless` dependency to this newest version.

2023-05-02 10:57 UTC, p-fernandez commented on .vscode/settings.json
> +                            "editor.codeActionsOnSave": {
I don't think this indentation is right.

2023-05-02 10:57 UTC, p-fernandez commented on packages/application-generic/src/factories/sms/handlers/africas-talking.handler.ts
> +    super('africastalking', ChannelTypeEnum.SMS);
```suggestion
    super('africas-talking', ChannelTypeEnum.SMS);
```
Based on the enum value set.

2023-05-02 10:57 UTC, p-fernandez commented on providers/africas-talking/src/lib/africas-talking.provider.ts
> +  id: 'africastalking';
```suggestion
  id: 'africas-talking';
```

2023-05-02 23:33 UTC, peoray commented
@p-fernandez resolved

2023-05-04 08:59 UTC, p-fernandez commented
> @p-fernandez resolved

We need a `pnpm install` to fix the lock file conflicts. 🙏🏻

2023-05-04 09:47 UTC, peoray commented
@p-fernandez Not sure what you mean, but I went ahead to pull in the latest changes and did a `pnpm install` as well as `npm run setup:project`

2023-05-04 09:49 UTC, p-fernandez commented
> @p-fernandez Not sure what you mean, but I went ahead to pull in the latest changes and did a `pnpm install` as well as `npm run setup:project`

Basically what you did. 😄

2023-05-04 16:18 UTC, p-fernandez commented on providers/africas-talking/src/lib/africas-talking.provider.ts
> +import AfricasTalking from 'africasTalking';
```suggestion
import AfricasTalking from 'africastalking';
```

2023-05-04 16:27 UTC, p-fernandez commented on providers/africas-talking/src/lib/africas-talking.provider.spec.ts
> +    // @ts-ignore
```suggestion
    // @ts-expect-error
```

2023-05-04 17:19 UTC, p-fernandez commented on providers/africas-talking/src/lib/africas-talking.provider.spec.ts
> +    from: '2585',
```suggestion
    from: '1234',
```

2023-05-04 19:27 UTC, merged