MongoDB maxPoolSize to env variable. Refs: #3425
novuhq/novu pull request #3437
Opened 2023-05-17 06:40 UTC by wouter-toppy

### What change does this PR introduce?
MongoDB maxPoolSize to an env variable

### Why was this change needed?

Closes #3425

### Other information (Screenshots)

2023-05-17 08:53 UTC, p-fernandez requested changes
Thanks for your contribution. 
🌟

2023-05-17 08:53 UTC, p-fernandez commented on apps/api/src/config/env-validator.ts
> +    default: 700,
Considering you are being warn in MongoDB Atlas that is over 500, maybe that should be the default limit. Same, for the .env files.
For Novu's own configuration we can set that feature flag once this is merged.

2023-05-17 13:02 UTC, wouter-toppy commented
@scopsy  done!

2023-05-22 09:02 UTC, p-fernandez approved these changes
🌟

2023-05-22 10:53 UTC, wouter-toppy commented
@p-fernandez  pipeline is still failing, what can we do about it? already did a rebase.

2023-05-22 11:14 UTC, p-fernandez commented
> @p-fernandez pipeline is still failing, what can we do about it? already did a rebase.

That error is something on our side. No worries. Thanks for pinging me.

2023-05-22 11:14 UTC, merged