Symfony Notifier in README.md
novuhq/novu pull request #3633
Opened 2023-06-21 08:06 UTC by wouter-toppy

Docment the existance of the symfony-notifier component

### What change does this PR introduce?

Provide the existance of the Symfony Notifier Component

### Why was this change needed?

Closes: #3632

### Other information (Screenshots)

https://github.com/symfony/novu-notifier

2023-06-21 09:07 UTC, p-fernandez requested changes
I am sorry but I consider this is not the right place to mention this integration with Novu, as the README is the main entry point to everything that related to Novu itself, what it does and how to use it.
@unicodeveloper would you mind to work with this contributor to find where is the best place we can showcase different tools or integrations implementing Novu for other languages and tools? 🙏🏻

2023-06-21 09:17 UTC, wouter-toppy commented
> I am sorry but I consider this is not the right place to mention this integration with Novu, as the README is the main entry point to everything that related to Novu itself, what it does and how to use it. @unicodeveloper would you mind to work with this contributor to find where is the best place we can showcase different tools or integrations implementing Novu for other languages and tools? 🙏🏻

@p-fernandez I agreed the readme is not the ideal place. but I did't find a good place to mention these sort of tools that integrates novu. Perhaps @unicodeveloper has a correct answer.

2023-06-22 14:47 UTC, michaldziuba03 commented
@wouter-toppy @unicodeveloper @p-fernandez 

Maybe it should be mentioned in PHP SDK readme?

2023-07-12 08:40 UTC, scopsy commented
@wouter-toppy I aggree with @michaldziuba03 that a better location for this is on the PHP quick start guide and on the PHP SDK readme. Connecting also @unicodeveloper to further assist finding a good place for this. Closing the PR for now 🙏

2023-07-12 08:40 UTC, closed without merging