feat(provider): Add Sendchamp SMS provider integration
novuhq/novu pull request #3656
Opened 2023-06-23 17:37 UTC by peoray

### What change does this PR introduce?
Add Sendchamp SMS provider integration

### Why was this change needed?

Closes #3637 

### Other information (Screenshots)

2023-06-25 16:07 UTC, BiswaViraj commented on apps/web/public/static/images/providers/dark/sendchamp.svg
I think this won't look good in dark mode.
Can you please replace it with this?
https://res.cloudinary.com/sendchamp/image/upload/v1647472665/Sendchamp%20Website/logos/SendchampWhite_kelitk.svg

2023-06-29 12:58 UTC, unicodeveloper commented on apps/web/public/static/images/providers/dark/sendchamp.svg
@peoray

2023-07-04 00:34 UTC, peoray commented on apps/web/public/static/images/providers/dark/sendchamp.svg
@unicodeveloper @BiswaViraj done

2023-07-11 14:39 UTC, unicodeveloper commented
@peoray Please can you resolve the conflicts?

2023-07-11 17:38 UTC, jainpawan21 commented
@peoray 
Thanks for your contribution 🎉
Can you please add step-by-step documentation also for this new provider?

2023-07-11 18:00 UTC, peoray commented
@unicodeveloper all done

2023-07-20 12:09 UTC, BiswaViraj commented
@peoray Can you please resolve the conflicts?

2023-07-20 17:22 UTC, BiswaViraj requested changes
@peoray Awesome stuff 🌟
Just a small change needed
Can you please add `Sendchamp` and `sendchamp` to this [file](https://github.com/novuhq/novu/blob/ac2a69d2fba5a5bc499b8e5d56008743f1b160cb/.cspell.json#L490)
So that it will fix the spelling error CI test

2023-07-20 17:26 UTC, BiswaViraj requested changes
Also can you please add documentation for it over [here](https://github.com/novuhq/novu/tree/next/docs/docs/channels/sms)

2023-07-20 18:55 UTC, peoray commented
@BiswaViraj documentation exists in another PR (#3719)

2023-07-20 18:58 UTC, peoray commented
@BiswaViraj done :)

2023-07-21 06:18 UTC, BiswaViraj approved these changes
🌟

2023-07-21 07:26 UTC, merged