Add Staging Web Pipeline
novuhq/novu pull request #4108
Opened 2023-09-05 18:06 UTC by Cliftonz

This Pull Request adds a new pipeline to run and update novu's staging deployment for web.

Updates the same way as dev.

2023-09-06 09:03 UTC, p-fernandez requested changes

2023-09-07 13:21 UTC, Cliftonz commented on .github/workflows/staging-deploy-web.yml
> +    environment: Development
No, because it is the same as the dev env but with production specs.

2023-09-07 13:22 UTC, Cliftonz commented on .github/workflows/staging-deploy-web.yml
> +          REACT_APP_LAUNCH_DARKLY_CLIENT_SIDE_ID: ${{ secrets.DEV_LAUNCH_DARKLY_CLIENT_SIDE_ID }}
Not at this time, the system is set up with the same variables as dev.

2023-09-07 13:34 UTC, p-fernandez commented on .github/workflows/staging-deploy-web.yml
> +          REACT_APP_LAUNCH_DARKLY_CLIENT_SIDE_ID: ${{ secrets.DEV_LAUNCH_DARKLY_CLIENT_SIDE_ID }}
I'd recommend not to do that as Launch Darkly provides the extra environment and we won't face the situations of someone touching the Dev env FF configuration and affecting staging, that as far as I remember we meant to have the closest situation as production for load testing and reliability testing. If I missed some of the nuances of the goal of Staging and it is meant to be a replica of Dev, we can go the way you suggest it. 👍🏻

2023-09-07 13:45 UTC, p-fernandez approved these changes
After what we discussed privately let's go with this configuration as we need to stress test the system as soon as possible.

2023-09-07 16:27 UTC, merged