fix: Bug fixed for add filter button in production
novuhq/novu pull request #4284
Opened 2023-10-01 14:49 UTC by sjcode99

### What change does this PR introduce?
This PR fixes the bug for the Add Filter button in production

The change was to enable the add filter button in the production environment.

Fixes #4254

2023-10-01 19:11 UTC, LetItRock requested changes
@sjcode99 left you a comment in the original ticket ;)

2023-10-02 12:03 UTC, sjcode99 commented
@LetItRock  updated the PR with the latest changes. Please verify it . Thanks

2023-10-02 15:47 UTC, LetItRock submitted a review, later dismissed
hey @sjcode99 👋 
almost there, you are doing great! 🙌 just noticed that we didn't cover all the filter cases, please take a look at the below screenshot ;)
![Screenshot 2023-10-02 at 17 45 53](https://github.com/novuhq/novu/assets/2607232/5bd2762e-cd51-45d6-bac0-9a4c08d89df1)

2023-10-02 17:23 UTC, sjcode99 commented
@LetItRock, Ohh!!😮 I have missed this. Changes update, Please have a look.

2023-10-03 15:22 UTC, scopsy requested changes
Thank you @sjcode99 looking good! Just a small thing here to fix this un-needed import

2023-10-03 15:22 UTC, scopsy commented on apps/web/src/pages/templates/filter/FilterModal.tsx
> +import { boolean } from 'zod';
This seems like it was imported by a mistake.

2023-10-03 15:22 UTC, scopsy commented on apps/web/src/pages/templates/workflow/SideBar/StepSettings.tsx
> +          disabled={false}
```suggestion
```

2023-10-03 15:52 UTC, sjcode99 commented
Hey @scopsy, removed the unnecessary import. Please have a look

2023-10-03 16:51 UTC, scopsy approved these changes

2023-10-05 10:04 UTC, sjcode99 commented
Hey @LetItRock  @scopsy . Seems my code is not yet merged. can you please help with this merge

2023-10-15 12:35 UTC, sjcode99 commented
Hey @LetItRock, it's been a long since I created PR and I can still see it's not merged. Is there any issue in the code which needs to be addressed?
Thanks :)

2023-10-15 13:32 UTC, merged