fix: fixed react flow link
novuhq/novu pull request #4302
Opened 2023-10-02 08:01 UTC by govardhanshah456

### What change does this PR introduce?

Made the React Flow Link More foundable.

### Why was this change needed?

closes #4266 

### Other information (Screenshots)
![image](https://github.com/novuhq/novu/assets/60037118/bbf5ca64-3aa5-47cf-b470-9a329a4b5c79)

2023-10-02 09:28 UTC, scopsy commented
@govardhanshah456 could you please keep the original color of the link and just move the position to be centered as you did but with 30px top margin?

2023-10-02 09:39 UTC, govardhanshah456 commented
I was going to keep original color only but then it is barely visible in dark mode so I changed it to deeppink:(image for refn)
![image](https://github.com/novuhq/novu/assets/60037118/946007d4-10b4-4252-9fe2-b5d3968d5d76)
when keeping hover one can notice but only when hover event occurs(image refn)
![image](https://github.com/novuhq/novu/assets/60037118/5eecad56-bb61-460f-b377-ae4715c204db)

So should i revert it back to original color considering above conditions?

2023-10-02 12:24 UTC, govardhanshah456 commented
> I see, could you please just move it to the center with the old color? And just moving it down by 30px?

You can refer the latest commit, I have made that changes on it only

2023-10-02 12:25 UTC, scopsy commented
@govardhanshah456 mind sharing a photo of how it looks after the changes?

2023-10-02 12:31 UTC, govardhanshah456 commented
> @govardhanshah456 mind sharing a photo of how it looks after the changes?

![image](https://github.com/novuhq/novu/assets/60037118/7cb179b4-4298-4155-a125-00e021cb1bc7)

2023-10-03 04:29 UTC, govardhanshah456 commented
@scopsy any other changes required?

2023-10-03 06:48 UTC, scopsy requested changes
Just a small adjustment here

2023-10-03 06:48 UTC, scopsy commented on apps/web/src/components/quick-start/common/Workflow.styles.tsx
> +    top: 11px;
```suggestion
    top: 25px;
```

2023-10-03 06:48 UTC, scopsy commented on apps/web/src/components/quick-start/common/Workflow.styles.tsx
> +    text-decoration: underline;
```suggestion
```

2023-10-03 06:48 UTC, scopsy commented on apps/web/src/components/quick-start/common/Workflow.styles.tsx
> +    text-decoration: underline;
```suggestion
```

2023-10-03 06:49 UTC, scopsy commented
@govardhanshah456 please comment on the original issue so I can assign you

2023-10-03 06:53 UTC, govardhanshah456 commented
> @govardhanshah456 please comment on the original issue so I can assign you

yes, did that, and commited the suggestions provided

2023-10-03 09:46 UTC, scopsy approved these changes

2023-10-03 13:15 UTC, govardhanshah456 commented
@scopsy Hey, can you assign this to me? i have commented on the issue as well for the same.

Thanks

2023-10-04 06:11 UTC, merged