feat(providers): add zulip
novuhq/novu pull request #4457
Opened 2023-10-07 20:43 UTC by michaldziuba03

### What change does this PR introduce?

This PR introduces Zulip provider for chat channel.

### Why was this change needed?

Closes #4380

### Other information (Screenshots)

![image](https://github.com/novuhq/novu/assets/43048524/97bd63ee-3aa8-4d6b-aa8e-a3973b964f45)

> It works in the same way as Discord chat provider

![image](https://github.com/novuhq/novu/assets/43048524/b12759d8-d353-4254-826a-87a2945ada81)

> Logo with square variant visible in workflow editor

![image](https://github.com/novuhq/novu/assets/43048524/88db5edf-adf7-4ee5-9799-fe261d9f3a54)

2023-10-07 20:50 UTC, michaldziuba03 commented on providers/zulip/src/lib/zulip.provider.ts
> +  }
Zulip doesn't return any message id either in response body or in headers.

Response shape from the webhook:

```json
{
	"result": "success",
	"msg": ""
}
```

2023-10-08 02:06 UTC, michaldziuba03 commented
Docs PR: https://github.com/novuhq/docs/pull/188

2023-10-26 22:40 UTC, Cliftonz commented
@michaldziuba03  Can you resolve these conflicts?

2023-10-29 16:49 UTC, michaldziuba03 commented
@Cliftonz git conflicts resolved

2023-10-31 11:42 UTC, Cliftonz requested changes

2023-10-31 11:42 UTC, Cliftonz commented on providers/zulip/README.md
> +    FILL IN THE INITIALIZATION USAGE
This needs to be filled in

2023-10-31 18:33 UTC, michaldziuba03 commented
@BiswaViraj @Cliftonz

2023-10-31 20:07 UTC, Cliftonz approved these changes

2023-10-31 20:08 UTC, merged