re-feat(provider): guilded provider added
novuhq/novu pull request #4494
Opened 2023-10-11 17:24 UTC by Kanav-Arora

### What change does this PR introduce?

Added Guilded chat provider as requested in #4382 

### Why was this change needed?

Closes #4382 

### Other information (Screenshots)

<img width="1440" alt="Screenshot 2023-10-11 at 10 49 10 PM" src="https://github.com/novuhq/novu/assets/62852363/cd06e981-b43e-470b-97b9-6dda1c186932">

<img width="1440" alt="Screenshot 2023-10-11 at 10 49 24 PM" src="https://github.com/novuhq/novu/assets/62852363/5af36c75-abe1-4623-8cb7-5d00b66a2d63">

2023-10-12 06:59 UTC, Kanav-Arora commented
Hi @Cliftonz 
Please review this

2023-10-12 15:24 UTC, Cliftonz requested changes
Dont forget your unit tests

2023-10-12 15:36 UTC, Kanav-Arora commented on providers/guilded/README.md
> +    FILL IN THE INITIALIZATION USAGE
Done

2023-10-12 15:49 UTC, Kanav-Arora commented
Hi I have made the requested changes
Just to confirm is provider.spec.ts the unit test file. Please help me with it

2023-10-12 18:00 UTC, Cliftonz commented
> Hi I have made the requested changes Just to confirm is provider.spec.ts the unit test file. Please help me with it

I would recommend looking at other providers or posting in the issue that you need help from other commutiy members.

2023-10-17 18:19 UTC, Cliftonz commented
@Kanav-Arora looks like there are a few conflicts that need resolved.

2023-10-18 13:11 UTC, Kanav-Arora commented
Hi 
I have resolved merge conflict

2023-10-18 13:58 UTC, Cliftonz commented
@scopsy Why is this PR showing over 150 commits?
I must be missing something

2023-10-23 13:19 UTC, Cliftonz commented
@Kanav-Arora Please fix the conflicts as I think we are getting close to merging this

2023-10-23 13:19 UTC, Cliftonz approved these changes
Fix the conflicts and we are ready to go

2023-10-23 14:03 UTC, Kanav-Arora commented
@Cliftonz Done 
Please merge

2023-11-22 18:15 UTC, closed without merging

2023-11-22 21:40 UTC, Cliftonz commented
@Kanav-Arora Did you purposely delete the repository?