fix: sender name in mandrill provider
novuhq/novu pull request #4568
Opened 2023-10-18 05:56 UTC by emersonliuuu

### What change does this PR introduce?

Fixed issue #4558 by implementing an additional parameter that Mandrill required. 
### Why was this change needed?

Closes #4558
### Other information (Screenshots)

2023-10-19 12:52 UTC, p-fernandez requested changes
Thank you for your contribution.
Once fixed the failing test this PR is good to go!

2023-10-19 12:52 UTC, p-fernandez commented on providers/mandrill/src/lib/mandrill.provider.spec.ts
You need to fix this test. In line 37 you need to add the check for `from_name` with the expectad value you gave in the `mockConfig` in line 6.

2023-10-19 13:20 UTC, emersonliuuu commented on providers/mandrill/src/lib/mandrill.provider.spec.ts
Thanks for pointing out the missing part!

2023-10-23 12:56 UTC, p-fernandez approved these changes
Thank you for your contribution. 🌟

2023-10-23 13:21 UTC, merged