chore: bump emailjs & @types/node
novuhq/novu pull request #4571
Opened 2023-10-18 07:42 UTC by dammy001

### What change does this PR introduce?

### Why was this change needed?

### Other information (Screenshots)

2023-10-18 07:43 UTC, dammy001 commented
@scopsy here is the PR. I also update the @types/node to match the node versions

2023-10-19 15:00 UTC, p-fernandez requested changes
Please would you mind to address the changes requested?
Also you upgraded the `@types/node` version, you should revert back to the original as the Node v18 update is not done in our side.
Also the target back to `es2017`.

2023-10-19 16:21 UTC, dammy001 commented
> Please would you mind to address the changes requested? Also you upgraded the `@types/node` version, you should revert back to the original as the Node v18 update is not done in our side. Also the target back to `es2017`.

@p-fernandez Since we're updating the node version, I think it's better to change the transpile target which should result in a smaller library size, unlocking lib features, and sometimes even (slightly) better performance. check here: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping for node target mapping

2023-10-19 16:26 UTC, p-fernandez commented
> > Please would you mind to address the changes requested? Also you upgraded the `@types/node` version, you should revert back to the original as the Node v18 update is not done in our side. Also the target back to `es2017`.
> 
> @p-fernandez Since we're updating the node version, I think it's better to change the transpile target which should result in a smaller library size, unlocking lib features, and sometimes even (slightly) better performance. check here: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping for node target mapping
> 
> I can revert to `ES2021` instead of `ESNext`. what do you think?
> 
> For the `@types/node` I think we should update it to match the node version.

I do agree but needs to be worked in the PR where the Node is upgraded so all the changes are together. Both of the changes I asked to revert. 🙏🏻

2023-10-19 16:33 UTC, dammy001 commented on apps/web/package.json
> +    "@types/react-table": "^7.7.12",
They are `devDependencies` that don't have to be part of the build. Adding the type definition to dependencies will make the dependency tree bloated.

2023-10-19 16:34 UTC, dammy001 commented
> > > Please would you mind to address the changes requested? Also you upgraded the `@types/node` version, you should revert back to the original as the Node v18 update is not done in our side. Also the target back to `es2017`.
> > 
> > 
> > @p-fernandez Since we're updating the node version, I think it's better to change the transpile target which should result in a smaller library size, unlocking lib features, and sometimes even (slightly) better performance. check here: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping for node target mapping
> > I can revert to `ES2021` instead of `ESNext`. what do you think?
> > For the `@types/node` I think we should update it to match the node version.
> 
> I do agree but needs to be worked in the PR where the Node is upgraded so all the changes are together. Both of the changes I asked to revert. 🙏🏻

@p-fernandez i get but i think this PR is pointing to the `node-upgrade` branch as advised by @scopsy

2023-10-19 16:43 UTC, p-fernandez commented on apps/web/package.json
> +    "@types/react-table": "^7.7.12",
Sorry, you are right. I missed that it was moved from dependency place.
Please keep this change!

2023-12-31 13:15 UTC, closed without merging