feat: Initial setup created for the Viber Chat provider
novuhq/novu pull request #4572
Opened 2023-10-18 07:59 UTC by firoz3130

### What change does this PR introduce?

PR raised for the issue #4367 

### Why was this PR needed?

This is a draft PR for the viber chat provider I am working on

### Other information

I am working on the correct implementation of the D7 network. Would like to discuss on it based on the code I have written

2023-10-18 14:21 UTC, Cliftonz requested changes

2023-10-18 14:21 UTC, Cliftonz commented on providers/d7-viber-chat/README.md
> +    FILL IN THE INITIALIZATION USAGE
This needs to be filled in

2023-10-18 14:21 UTC, Cliftonz commented on providers/d7-viber-chat/package.json
> +  "version": "0.16.3",
The version needs to be updated to the .20 something like the rest of the providers

2023-10-22 03:17 UTC, firoz3130 commented
Can you review this @Cliftonz ?

2023-10-26 12:27 UTC, Cliftonz approved these changes

2023-10-26 12:33 UTC, firoz3130 commented
> @firoz3130 Looks like the testing pipeline failed due to the word "Firos" in the test.
> I would recommend adding it to the cspell file.

I have added that word in the cspell file 
But I haven't pushed that file here.@Cliftonz

2023-10-26 13:44 UTC, firoz3130 commented
Any things I have to add upon here @Cliftonz ?

2023-10-29 15:04 UTC, firoz3130 commented
If you can, please add hacktoberfest label in this pr?@Cliftonz

2023-10-29 17:48 UTC, Cliftonz commented
@firoz3130 done

2024-04-07 16:01 UTC, closed without merging