fix: changed invite members icon in header Nav (when avatar is clicked)
novuhq/novu pull request #4622
Opened 2023-10-23 08:40 UTC by maverox

### What change does this PR introduce?

changed the invite-members icon to a more appropriate icon, in the header nav.

### Why was this change needed?

 Closes #4601 

### Code Changes
- created a new component called InviteMembers.tsx 
- pasted the code from Trash.tsx and replaced svg with the one mentioned in the issue's figma design
- and changed all the <Mail /> in HeaderNav.tsx with <InviteMembers /> component
### Screenshot 

![Screenshot 2023-10-23 135953](https://github.com/novuhq/novu/assets/29498864/00ba14c4-b64a-46e9-960a-408c3cb81942)
![Screenshot 2023-10-23 135945](https://github.com/novuhq/novu/assets/29498864/74b4dcb0-a49a-48a5-9de3-b4c99545a022)

2023-10-23 13:27 UTC, p-fernandez requested changes

2023-10-23 13:27 UTC, p-fernandez commented on apps/web/src/design-system/icons/general/inviteMembers.tsx
The filename should be `InviteMembers.tsx` with Pascal casing. This makes the project to break and not build the Web app. Please fix it.

2023-10-24 11:01 UTC, maverox commented on apps/web/src/design-system/icons/general/inviteMembers.tsx
I am really not sure how this is possible,  I renamed the file and changed it. But nonetheless, I am working on it.

2023-10-24 11:04 UTC, closed without merging

2023-10-24 11:28 UTC, p-fernandez commented on apps/web/src/design-system/icons/general/inviteMembers.tsx
You need to do: `git mv inviteMembers.tsx InviteMembers.tsx`
The problem is the version control has registered that name and you need to tell the version control that the file name has changed by using [`git mv`](https://git-scm.com/docs/git-mv).