feat(provider): added simple-texting SMS provider
novuhq/novu pull request #4650
Opened 2023-10-25 10:44 UTC by parveshsaini

### What change does this PR introduce?

- Introduces SimpleTexting SMS provider
- Doc Reference: https://simpletexting.com/api/docs/v2/

### Why was this change needed?

- Closes: https://github.com/novuhq/novu/issues/4342

### Other information (Screenshots)

![image](https://github.com/novuhq/novu/assets/97528080/dd29c27b-5841-4e3e-a57d-0b3a16878483)

![image](https://github.com/novuhq/novu/assets/97528080/5071a544-cb6d-4038-a595-952840d67078)

2023-10-29 12:01 UTC, Cliftonz approved these changes

2023-10-29 12:02 UTC, Cliftonz commented
@parveshsaini looks like there are some conflicts to fix.

2023-10-29 17:08 UTC, parveshsaini commented
> @parveshsaini looks like there are some conflicts to fix.

done 🚀

2023-10-30 16:07 UTC, BiswaViraj requested changes
Looks good,
Can you please fix the failing tests and also add the provider to this list [here](https://github.com/novuhq/novu/blob/524f18bde28296d2e706ca05762d3bb1b28f6b70/apps/web/src/pages/integrations/components/multi-provider/sort-providers.ts#L71C35-L71C35)

2023-10-30 16:15 UTC, BiswaViraj requested changes

2023-10-30 16:15 UTC, BiswaViraj commented on providers/simpletexting/package.json
> +    "@novu/stateless": "0.16.3",
```suggestion
    "@novu/stateless": "0.21.0",
```

2023-10-30 19:37 UTC, parveshsaini commented
hey @BiswaViraj 
Can you please guide me on how to fix the failing tests

2023-10-31 05:16 UTC, BiswaViraj commented
@parveshsaini, you can ignore the other failing tests as those are something from our side,
For now please fix the spell check test by adding the word to the .cspell.json file

2023-10-31 11:18 UTC, parveshsaini commented
hi @BiswaViraj 
I've updated .cspell.json

2023-10-31 11:33 UTC, Cliftonz approved these changes

2023-10-31 13:18 UTC, Cliftonz commented
@parveshsaini  looks like we need to resolve some conflicts, this may happen a few times so just be prepared.

2023-10-31 15:06 UTC, parveshsaini commented
> @parveshsaini looks like we need to resolve some conflicts, this may happen a few times so just be prepare

🫡

2023-10-31 15:21 UTC, parveshsaini commented
conflicts resolved 🚀
@BiswaViraj @Cliftonz

2023-10-31 15:46 UTC, BiswaViraj commented
@parveshsaini Cool will merge it once the test CI finishes

2023-10-31 16:50 UTC, BiswaViraj approved these changes

2023-10-31 16:51 UTC, merged