feat: Added MessageBird SMS client
novuhq/novu pull request #4687
Opened 2023-10-28 13:13 UTC by ayushshukla7777

### What change does this PR introduce?
This commit adds the MessageBird SMS client to our project.

### Why was this change needed?

Closes #4386

### Other information (Screenshots)
![image](https://github.com/novuhq/novu/assets/53791140/90e2fee8-5f4f-4d1d-8db3-7051592a47a4)
![image](https://github.com/novuhq/novu/assets/53791140/89abb3e2-e686-4761-b262-0f62db36e34c)
![image](https://github.com/novuhq/novu/assets/53791140/b9954286-1d1c-458f-9bd0-bb34fe60199d)

2023-10-28 19:40 UTC, Cliftonz requested changes

2023-10-28 19:40 UTC, Cliftonz commented on packages/application-generic/package.json
> +    "@novu/messagebird": "^0.16.3",
version should be the same as the rest

2023-10-28 19:40 UTC, Cliftonz commented on providers/messagebird/package.json
> +  "version": "0.16.3",
Same as above

2023-10-28 19:40 UTC, Cliftonz commented on providers/messagebird/README.md
> +# MessageBird Node.js API Client
It looks like you just copy pasted the docs for the client, please look at some of the other providers and make this Novu centric.

2023-10-28 20:41 UTC, ayushshukla7777 commented
hey @Cliftonz , Did the changes as you requested.

2023-10-28 20:59 UTC, Cliftonz commented
Looks like the cspell pipeline failed, you will need to add these two words will need to be added to the cspell list.
![CleanShot 2023-10-28 at 16 54 19@2x](https://github.com/novuhq/novu/assets/43915749/0daadc8f-a9c4-4e4c-8f56-821b0562821e)

2023-10-28 21:21 UTC, ayushshukla7777 commented
hey @Cliftonz , Added them to cspell

2023-10-29 11:43 UTC, Cliftonz approved these changes

2023-10-29 11:45 UTC, merged