feat: add getstream
novuhq/novu pull request #4692
Opened 2023-10-29 15:48 UTC by vikaspatil0021

### What change does this PR introduce?

### Why was this change needed?

### Other information (Screenshots)

2023-11-01 13:40 UTC, Cliftonz requested changes

2023-11-01 13:40 UTC, Cliftonz commented on providers/getstream/README.md
> +const provider = new GetstreamChatProvider({});
this should contain the API key as defined in the provider

2023-11-01 13:40 UTC, Cliftonz commented on providers/getstream/package.json
> +  "version": "0.16.3",
this should be 0.21.0

2023-11-01 13:40 UTC, Cliftonz commented on packages/application-generic/package.json
> +    "@novu/getstream": "^0.16.3",
This should be 0.21.0

2023-11-01 16:28 UTC, vikaspatil0021 commented
Hey @Cliftonz  Requested changes have been updated :)

2023-11-01 17:54 UTC, Cliftonz commented
@vikaspatil0021 Looks like we need to resolve some conflicts, please be patient we are merging alot of providers and may need to do this a few time.

2023-11-05 15:21 UTC, Cliftonz commented
Can you resolve these conflicts?

2023-11-06 02:33 UTC, vikaspatil0021 commented
@Cliftonz Yes, I can resolve them

2023-11-11 16:01 UTC, Cliftonz commented
@vikaspatil0021 Looks like we need to resolve some conflicts again, please be patient we are merging alot of providers and may need to do this a few time.

2023-11-11 16:02 UTC, Cliftonz commented
@vikaspatil0021 Looks like we need to resolve some conflicts again, please be patient we are merging alot of providers and may need to do this a few time.

2023-11-21 02:10 UTC, vikaspatil0021 commented
Hey @Cliftonz , any updates?

2023-11-23 21:36 UTC, Cliftonz commented
@vikaspatil0021 Hey things have stabilized, if you fix the conflicts listed here and @ me again I should be able to get it merged.

2023-11-24 02:47 UTC, vikaspatil0021 commented
Hi @Cliftonz, I've fixed the conflicts. Can you please check it?

2023-11-24 14:17 UTC, Cliftonz commented
@vikaspatil0021 looks like we have a few unknow words in this pr. Can you fix them?
https://github.com/novuhq/novu/actions/runs/6976284336/job/18996272086?pr=4692

2023-11-25 03:27 UTC, vikaspatil0021 commented
Hi @Cliftonz, I've updated the `.cspell.json` file by including both "getstream" and "Getstream" in the list of recognized words. Kindly review and confirm.

2023-11-25 14:36 UTC, vikaspatil0021 commented
Hey @Cliftonz , could you please review and approve the workflows again? I believe there is one final check that needs to be fixed.

2023-11-25 16:02 UTC, vikaspatil0021 commented
@Cliftonz  I've made modifications to the files **digest-events.e2e.ts** and **commands.ts**. Kindly reconsider approving the workflow once again.

2023-11-26 03:31 UTC, vikaspatil0021 commented
@Cliftonz  I've made more changes to the **digest-events.e2e.ts** and **user-preference.spec.ts** files. Please review and approve these modifications once again.

2023-11-26 22:30 UTC, merged