refactor(providers): Migrate from onesignal-node SDK to the official @onesignal/node-onesignal
novuhq/novu pull request #4840
Opened 2023-11-13 14:00 UTC by Dhoni77

### What change does this PR introduce?

- Remove onesignal-node sdk
- Use `@onesignal/node-onesignal` sdk
- Updated unit tests

### Why was this change needed?

Closes #4635

Due to vulnerabilities and un-maintained SDK, we should move from using unofficial onesignal-node SDK.

2023-11-14 07:51 UTC, scopsy commented on packages/application-generic/src/factories/push/handlers/one-signal.handler.ts
> +      userKey: credentials.userKey,
Unfortunately this change is causing a breakin change for all of one signal users, is there some mapping between the old apiKey to the new appKey? is that the same value?

2023-11-14 07:51 UTC, scopsy requested changes
We need to make sure that we are not providing a breaking change for old configuration users who used the apiKey and applicationId approach.

2023-11-14 07:54 UTC, scopsy commented
@Dhoni77 another approach we can take is using the rest API directly which works with API key and AppId like previously: https://documentation.onesignal.com/reference/create-notification we can use axios for the API call, wdyt?

2023-11-14 11:57 UTC, Dhoni77 commented on providers/one-signal/package.json
> +    "axios": "1.3.4"
Ok👍

2023-11-15 13:14 UTC, scopsy commented on providers/one-signal/src/lib/one-signal.provider.spec.ts
> +import { IPushOptions } from 'packages/stateless/build/main';
```suggestion
import { IPushOptions } from '@novu/stateless';
```

2023-11-18 09:53 UTC, scopsy approved these changes

2023-11-20 12:56 UTC, merged