Added iSend SMS Provider
novuhq/novu pull request #5000
Opened 2023-12-18 12:16 UTC by Saff-Elli-Khan

### What change does this PR introduce?

Added a new SMS provider called isend-sms. isend is a Libyan SMS provider company which provides services just in Libya and is cheaper compared to Twilio or any other provider, for Libyan developers.

### Why was this change needed?

Support for a Libyan SMS provider company isend-sms https://send.com.ly/

2023-12-18 13:55 UTC, Cliftonz requested changes

2023-12-18 13:55 UTC, Cliftonz commented on packages/application-generic/package.json
> +    "@novu/isend-sms": "^0.16.3",
This should be the same as the other providers

2023-12-18 13:55 UTC, Cliftonz commented on providers/isend-sms/package.json
> +  "version": "0.16.3",
This should be updated to the current version

2023-12-18 19:30 UTC, Cliftonz commented
@Saff-Elli-Khan The CI is failing on a unit test and there is a missing cspell value

2023-12-19 11:41 UTC, Saff-Elli-Khan commented
@Cliftonz I have fixed the spelling test, but I have no idea why other tests are failing in the CI, I added the provider exactly according to the docs provided by Novu. It is really confusing to me can you please point out where is the problem?

2023-12-19 14:57 UTC, rifont commented on providers/isend-sms/jest.config.js
> +  testEnvironment: 'node',
To resolve the Jest test issue [here](https://github.com/novuhq/novu/actions/runs/7260977977/job/19781519293?pr=5000#step:5:71), a module name mapper is required due to Jest's lack of support for ES modules.

An example in another provider is available [here](https://github.com/novuhq/novu/blob/1950a191ffb351875c7d79a16237ed9e23000226/providers/resend/jest.config.js#L6).
```suggestion
  testEnvironment: 'node',
  moduleNameMapper: {
    axios: 'axios/dist/node/axios.cjs',
  },
```

2023-12-19 23:47 UTC, Saff-Elli-Khan commented
@Cliftonz @rifont the test is still failing for some reason! Can you please help? I really need this provider on production asap!

2024-01-05 13:35 UTC, Cliftonz approved these changes

2024-01-05 13:36 UTC, Cliftonz commented
@Saff-Elli-Khan this provider should be out in the next release around the beginning of February

2024-01-05 13:36 UTC, merged

2024-01-05 13:42 UTC, Saff-Elli-Khan commented
> @Saff-Elli-Khan this provider should be out in the next release around the beginning of February

Great! Thanks :)