Nv 3147
novuhq/novu pull request #5073
Opened 2024-01-11 22:06 UTC by antonjoel82

### What change does this PR introduce?

- Introduces test to catch issue with saving variants with empty conditions
- Disable submit button and add tooltip when removing all conditions from a variant

### Why was this change needed?

Fixes NV-3147 

### Other information (Screenshots)

![](https://github.com/novuhq/novu/assets/47441786/504913d7-34f2-41fe-bf55-ef6c4fa87e97)

2024-01-11 22:10 UTC, antonjoel82 commented on apps/web/src/components/conditions/Conditions.tsx
> +  shouldDisallowEmptyConditions?: boolean;
Flag here is optional / opt-in to preserve the original functionality for other callers of this component.

2024-01-12 16:45 UTC, BiswaViraj requested changes
@antonjoel82, Sorry for not adding this in the task description
But we will need to update the API too to disallow update of empty conditions variants.
[more details](https://linear.app/novu/issue/NV-3147/🔀-able-to-save-variants-without-any-conditions#comment-26036b30)

2024-01-12 19:59 UTC, antonjoel82 commented
> @antonjoel82, Sorry for not adding this in the task description But we will need to update the API too to disallow update of empty conditions variants. [more details](https://linear.app/novu/issue/NV-3147/%F0%9F%94%80-able-to-save-variants-without-any-conditions#comment-26036b30)

Sounds good, thanks for the call-out! I would typically do those in two different PRs, but am happy to do that in this PR as well if that's the preferred way.

2024-01-12 20:22 UTC, BiswaViraj commented
@antonjoel82, it will be better to have two different PRs. I thought API changes were might be overlooked due to not being in the task description 🙏 🙈.
Also just how linear works, I'll suggest you to create a sub-issue for API over linear and tackle it on that task. This way we will have our linear and prs synced.
Let me know if you need anything.

2024-01-12 22:36 UTC, antonjoel82 commented
> @antonjoel82, it will be better to have two different PRs. I thought API changes were might be overlooked due to not being in the task description 🙏 🙈. Also just how linear works, I'll suggest you to create a sub-issue for API over linear and tackle it on that task. This way we will have our linear and prs synced. Let me know if you need anything.

Great, thank you! I'll update this PR description to make it more explicit, and have created a [sub-issue](https://linear.app/novu/issue/NV-3363/prevent-saving-variants-without-any-conditions-on-the-server) as requested.

2024-01-16 15:24 UTC, BiswaViraj approved these changes
🚀

2024-01-17 14:01 UTC, LetItRock approved these changes
awesome work!🔥 verified it with the dev testing and works like a charm :) let's now also implement the changes on API side :)

2024-01-17 16:34 UTC, merged