feat(provider): add ring central provider (#77)
novuhq/novu pull request #5147
Opened 2024-02-01 22:14 UTC by KelvisGama

### What change does this PR introduce?

Add [RingCentral ](https://www.ringcentral.com/) provider implementation

### Why was this change needed?
Closes #77 

### Other information (Screenshots)

#### Integration Store
![image](https://github.com/novuhq/novu/assets/17547143/7102d871-5de8-4df1-b608-8dae32ba9239)

#### Workflow
![image](https://github.com/novuhq/novu/assets/17547143/15ccd62d-82d6-4ba0-b848-1e9910d32b99)

#### Activity Feed

![image](https://github.com/novuhq/novu/assets/17547143/cf8b5d73-fca2-4e92-ac0e-5319bafbc820)

2024-02-02 12:07 UTC, jainpawan21 requested changes

2024-02-02 12:07 UTC, jainpawan21 commented on apps/web/public/static/images/providers/dark/ring-central.svg
@KelvisGama could you please add square logo svgs in dark and light square folders?

Ref:- https://docs.novu.co/community/add-a-new-provider#add-provider-logos

2024-02-02 16:02 UTC, KelvisGama commented on apps/web/public/static/images/providers/dark/ring-central.svg
@jainpawan21 Those already exist.
They are added on https://github.com/novuhq/novu/commit/e9abbd25de69e3a1359a1ace98e824b2770cabe6

2024-02-02 21:23 UTC, KelvisGama commented on packages/application-generic/package.json
> -    "@nestjs/passport": "^10.0.1",
It was duplicated. (line 53)

2024-02-05 19:24 UTC, Cliftonz approved these changes

2024-02-05 19:25 UTC, Cliftonz commented
@KelvisGama Please add the words missing in the spell check pipeline to this PR
https://github.com/novuhq/novu/actions/runs/7788071814/job/21242085435?pr=5147

2024-02-07 00:20 UTC, merged